USE SUPERMARKET;

select *from employee;
select *from BRANCH;
select *from product;
select *from CUSTOMER;
select *from bill;
select *from `transaction`;


SELECT BRANCH_NAME FROM EMPLOYEE,BRANCH WHERE EMPLOYEE.BRANCH_ID=BRANCH.BRANCH_ID AND EMPLOYEE.EMP_ID=2;

SELECT T.TID,T.PID,P.PRODUCT_NAME,C.CUSTOMER_ID,CUSTOMER_NAME,C.PH_NO,T.QUANTITY FROM (`TRANSACTION` AS T,BILL AS B,CUSTOMER AS C, PRODUCT AS P) WHERE T.TID=B.TID AND B.CUSTOMER_ID=C.CUSTOMER_ID AND T.PID=P.PRODUCT_ID AND EXISTS (SELECT * FROM EMPLOYEE AS E WHERE E.EMP_ID=B.EMP_ID AND E.BRANCH_ID=2);